-- =============================================================================
-- Seed da Fase 1 — Empoeirar (produtos + variantes)
-- Idempotente por slug. Precos em centavos; dimensoes em mm. weight_grams = null.
-- =============================================================================

-- ---- Categorias -------------------------------------------------------------
insert into public.category (name, slug, description, sort_order, is_custom_funnel) values
  ('Conjuntos Orgânicos',          'conjuntos-organicos',  'Conjuntos de moldes de formas orgânicas, com nomes em homenagem ao Vale do Jequitinhonha.', 1, false),
  ('Moldes Geométricos',           'moldes-geometricos',   'Círculos, quadrados, retângulos e elipses, em conjuntos do PP ao GG.',                      2, false),
  ('Moldes Lúdicos',               'moldes-ludicos',       'Moldes de frutas, bichos e figuras para peças cheias de personalidade.',                    3, false),
  ('Especiais',                    'especiais',            'Moldes para peças de mesa: pratos de risoto, copos, bowls e conjuntos de sushi.',           4, false),
  ('Ferramentas',                  'ferramentas',          'Discos para torno, réguas niveladoras e acessórios em MDF naval, resistentes à água.',      5, false),
  ('Um molde para chamar de seu!', 'molde-personalizado',  'Desenhe, fotografe ou imagine: transformamos sua ideia num molde único e exclusivo.',       6, true)
on conflict (slug) do nothing;

-- ---- Produtos ---------------------------------------------------------------
insert into public.product
  (category_id, name, slug, description, status, stock, material_care)
values
  ((select id from public.category where slug = 'conjuntos-organicos'), 'Conjunto Turmalina', 'conjunto-turmalina', 'Conjunto de moldes orgânicos com puxadores entalhados para desmoldar sem marcar a borda. Homenagem ao Vale do Jequitinhonha.', 'published', 5, 'Feito à mão em MDF de 18 mm. Mantenha em local seco; limpe com pano levemente úmido, sem imergir em água.'),
  ((select id from public.category where slug = 'conjuntos-organicos'), 'Conjunto Padre Paraíso', 'conjunto-padre-paraiso', 'Conjunto de cinco moldes orgânicos (do PP ao GG), com puxadores entalhados. Homenagem ao Vale do Jequitinhonha.', 'published', 5, 'Feito à mão em MDF de 18 mm. Mantenha em local seco; limpe com pano levemente úmido, sem imergir em água.'),
  ((select id from public.category where slug = 'conjuntos-organicos'), 'Conjunto Joaíma', 'conjunto-joaima', 'Conjunto de moldes orgânicos (P, M e G) com puxadores entalhados. Homenagem ao Vale do Jequitinhonha.', 'published', 5, 'Feito à mão em MDF de 18 mm. Mantenha em local seco; limpe com pano levemente úmido, sem imergir em água.'),
  ((select id from public.category where slug = 'conjuntos-organicos'), 'Conjunto Caraí', 'conjunto-carai', 'Conjunto de cinco moldes orgânicos (do PP ao GG), do petisco à travessa. Homenagem ao Vale do Jequitinhonha.', 'published', 5, 'Feito à mão em MDF de 18 mm. Mantenha em local seco; limpe com pano levemente úmido, sem imergir em água.'),
  ((select id from public.category where slug = 'conjuntos-organicos'), 'Conjunto Itaobim', 'conjunto-itaobim', 'Conjunto de moldes orgânicos alongados (P, M e G). Homenagem ao Vale do Jequitinhonha.', 'published', 5, 'Feito à mão em MDF de 18 mm. Mantenha em local seco; limpe com pano levemente úmido, sem imergir em água.'),
  ((select id from public.category where slug = 'conjuntos-organicos'), 'Conjunto Minas Novas', 'conjunto-minas-novas', 'Conjunto de moldes orgânicos (P, M e G) com puxadores entalhados. Homenagem ao Vale do Jequitinhonha.', 'published', 5, 'Feito à mão em MDF de 18 mm. Mantenha em local seco; limpe com pano levemente úmido, sem imergir em água.'),
  ((select id from public.category where slug = 'conjuntos-organicos'), 'Conjunto Itinga', 'conjunto-itinga', 'Conjunto de moldes orgânicos arredondados (P, M e G). Homenagem ao Vale do Jequitinhonha.', 'published', 5, 'Feito à mão em MDF de 18 mm. Mantenha em local seco; limpe com pano levemente úmido, sem imergir em água.'),
  ((select id from public.category where slug = 'conjuntos-organicos'), 'Conjunto Taiobeiras', 'conjunto-taiobeiras', 'Conjunto de moldes orgânicos (P, M e G) com puxadores entalhados. Homenagem ao Vale do Jequitinhonha.', 'published', 5, 'Feito à mão em MDF de 18 mm. Mantenha em local seco; limpe com pano levemente úmido, sem imergir em água.'),
  ((select id from public.category where slug = 'conjuntos-organicos'), 'Conjunto Araçuaí', 'conjunto-aracuai', 'Conjunto de moldes orgânicos alongados (P, M e G). Homenagem ao Vale do Jequitinhonha.', 'published', 5, 'Feito à mão em MDF de 18 mm. Mantenha em local seco; limpe com pano levemente úmido, sem imergir em água.'),
  ((select id from public.category where slug = 'conjuntos-organicos'), 'Conjunto Pasmado', 'conjunto-pasmado', 'Conjunto de cinco moldes orgânicos (do PP ao GG), com puxadores entalhados. Homenagem ao Vale do Jequitinhonha.', 'published', 5, 'Feito à mão em MDF de 18 mm. Mantenha em local seco; limpe com pano levemente úmido, sem imergir em água.'),
  ((select id from public.category where slug = 'moldes-geometricos'), 'Círculos', 'circulos', 'Conjunto de cinco moldes circulares (de 14 a 38 cm), do PP ao GG.', 'published', 5, 'Feito à mão em MDF de 18 mm. Mantenha em local seco; limpe com pano levemente úmido, sem imergir em água.'),
  ((select id from public.category where slug = 'moldes-geometricos'), 'Quadrados', 'quadrados', 'Conjunto de cinco moldes quadrados (de 14 a 38 cm), do PP ao GG.', 'published', 5, 'Feito à mão em MDF de 18 mm. Mantenha em local seco; limpe com pano levemente úmido, sem imergir em água.'),
  ((select id from public.category where slug = 'moldes-geometricos'), 'Retângulos', 'retangulos', 'Conjunto de cinco moldes retangulares (de 14 a 38 cm de comprimento), do PP ao GG.', 'published', 5, 'Feito à mão em MDF de 18 mm. Mantenha em local seco; limpe com pano levemente úmido, sem imergir em água.'),
  ((select id from public.category where slug = 'moldes-geometricos'), 'Elipses', 'elipses', 'Conjunto de cinco moldes em elipse (do PP ao GG) para pratos e travessas ovais.', 'published', 5, 'Feito à mão em MDF de 18 mm. Mantenha em local seco; limpe com pano levemente úmido, sem imergir em água.'),
  ((select id from public.category where slug = 'moldes-ludicos'), 'Pães de Forma', 'paes-de-forma', 'Conjunto de dois moldes em formato de pão de forma.', 'published', 5, 'Feito à mão em MDF de 18 mm. Mantenha em local seco; limpe com pano levemente úmido, sem imergir em água.'),
  ((select id from public.category where slug = 'moldes-ludicos'), 'Pizza', 'pizza', 'Molde em formato de fatia de pizza.', 'published', 5, 'Feito à mão em MDF de 18 mm. Mantenha em local seco; limpe com pano levemente úmido, sem imergir em água.'),
  ((select id from public.category where slug = 'moldes-ludicos'), 'Ovos', 'ovos', 'Trio de moldes em formato de ovo, para pratinhos e petisqueiras.', 'published', 5, 'Feito à mão em MDF de 18 mm. Mantenha em local seco; limpe com pano levemente úmido, sem imergir em água.'),
  ((select id from public.category where slug = 'moldes-ludicos'), 'Ovo Frito Com Gema', 'ovo-frito-com-gema', 'Molde divertido em formato de ovo frito com gema.', 'published', 5, 'Feito à mão em MDF de 18 mm. Mantenha em local seco; limpe com pano levemente úmido, sem imergir em água.'),
  ((select id from public.category where slug = 'moldes-ludicos'), 'Banana', 'banana', 'Molde em formato de banana.', 'published', 5, 'Feito à mão em MDF de 18 mm. Mantenha em local seco; limpe com pano levemente úmido, sem imergir em água.'),
  ((select id from public.category where slug = 'moldes-ludicos'), 'Limão Siciliano', 'limao-siciliano', 'Molde em formato de limão siciliano.', 'published', 5, 'Feito à mão em MDF de 18 mm. Mantenha em local seco; limpe com pano levemente úmido, sem imergir em água.'),
  ((select id from public.category where slug = 'moldes-ludicos'), 'Maçã', 'maca', 'Molde em formato de maçã.', 'published', 5, 'Feito à mão em MDF de 18 mm. Mantenha em local seco; limpe com pano levemente úmido, sem imergir em água.'),
  ((select id from public.category where slug = 'moldes-ludicos'), 'Pêra', 'pera', 'Molde em formato de pêra.', 'published', 5, 'Feito à mão em MDF de 18 mm. Mantenha em local seco; limpe com pano levemente úmido, sem imergir em água.'),
  ((select id from public.category where slug = 'moldes-ludicos'), 'Melancia', 'melancia', 'Molde em formato de fatia de melancia.', 'published', 5, 'Feito à mão em MDF de 18 mm. Mantenha em local seco; limpe com pano levemente úmido, sem imergir em água.'),
  ((select id from public.category where slug = 'moldes-ludicos'), 'Todas as Frutas', 'todas-as-frutas', 'Conjunto com os cinco moldes de frutas: banana, limão siciliano, maçã, melancia e pêra.', 'published', 5, 'Feito à mão em MDF de 18 mm. Mantenha em local seco; limpe com pano levemente úmido, sem imergir em água.'),
  ((select id from public.category where slug = 'moldes-ludicos'), 'Capivaras', 'capivaras', 'Conjunto de dois moldes em formato de capivara.', 'published', 5, 'Feito à mão em MDF de 18 mm. Mantenha em local seco; limpe com pano levemente úmido, sem imergir em água.'),
  ((select id from public.category where slug = 'moldes-ludicos'), 'Gatinhos', 'gatinhos', 'Conjunto de dois moldes em formato de gatinho.', 'published', 5, 'Feito à mão em MDF de 18 mm. Mantenha em local seco; limpe com pano levemente úmido, sem imergir em água.'),
  ((select id from public.category where slug = 'moldes-ludicos'), 'Conchas', 'conchas', 'Conjunto de três moldes em formato de concha.', 'published', 5, 'Feito à mão em MDF de 18 mm. Mantenha em local seco; limpe com pano levemente úmido, sem imergir em água.'),
  ((select id from public.category where slug = 'moldes-ludicos'), 'Ursinhos', 'ursinhos', 'Conjunto de dois moldes em formato de ursinho.', 'published', 5, 'Feito à mão em MDF de 18 mm. Mantenha em local seco; limpe com pano levemente úmido, sem imergir em água.'),
  ((select id from public.category where slug = 'moldes-ludicos'), 'Bonecos de Biscoito', 'bonecos-de-biscoito', 'Conjunto de três moldes em formato de boneco de biscoito.', 'published', 5, 'Feito à mão em MDF de 18 mm. Mantenha em local seco; limpe com pano levemente úmido, sem imergir em água.'),
  ((select id from public.category where slug = 'moldes-ludicos'), 'Estrelas', 'estrelas', 'Conjunto de três moldes em formato de estrela.', 'published', 5, 'Feito à mão em MDF de 18 mm. Mantenha em local seco; limpe com pano levemente úmido, sem imergir em água.'),
  ((select id from public.category where slug = 'moldes-ludicos'), 'Árvore de Natal', 'arvore-de-natal', 'Molde em formato de árvore de Natal, para peças de fim de ano.', 'published', 5, 'Feito à mão em MDF de 18 mm. Mantenha em local seco; limpe com pano levemente úmido, sem imergir em água.'),
  ((select id from public.category where slug = 'moldes-ludicos'), 'Corações', 'coracoes', 'Conjunto de dois moldes em formato de coração.', 'published', 5, 'Feito à mão em MDF de 18 mm. Mantenha em local seco; limpe com pano levemente úmido, sem imergir em água.'),
  ((select id from public.category where slug = 'moldes-ludicos'), 'Luas', 'luas', 'Conjunto de dois moldes em formato de lua.', 'published', 5, 'Feito à mão em MDF de 18 mm. Mantenha em local seco; limpe com pano levemente úmido, sem imergir em água.'),
  ((select id from public.category where slug = 'moldes-ludicos'), 'Nuvens', 'nuvens', 'Conjunto de dois moldes em formato de nuvem.', 'published', 5, 'Feito à mão em MDF de 18 mm. Mantenha em local seco; limpe com pano levemente úmido, sem imergir em água.'),
  ((select id from public.category where slug = 'moldes-ludicos'), 'Barcos', 'barcos', 'Conjunto de dois moldes em formato de barco.', 'published', 5, 'Feito à mão em MDF de 18 mm. Mantenha em local seco; limpe com pano levemente úmido, sem imergir em água.'),
  ((select id from public.category where slug = 'moldes-ludicos'), 'Canoa', 'canoa', 'Molde alongado em formato de canoa.', 'published', 5, 'Feito à mão em MDF de 18 mm. Mantenha em local seco; limpe com pano levemente úmido, sem imergir em água.'),
  ((select id from public.category where slug = 'especiais'), 'Conjunto Sushi Arredondado', 'conjunto-sushi-arredondado', 'Conjunto de três moldes para pratos de sushi com cantos arredondados.', 'published', 5, 'Feito à mão em MDF de 18 mm. Mantenha em local seco; limpe com pano levemente úmido, sem imergir em água.'),
  ((select id from public.category where slug = 'especiais'), 'Conjunto Sushi Reto', 'conjunto-sushi-reto', 'Conjunto de três moldes para pratos de sushi de linhas retas.', 'published', 5, 'Feito à mão em MDF de 18 mm. Mantenha em local seco; limpe com pano levemente úmido, sem imergir em água.'),
  ((select id from public.category where slug = 'especiais'), 'Prato de Risoto', 'prato-de-risoto', 'Molde para prato de risoto com aba larga e centro fundo: 31 cm de diâmetro e 7,2 cm de altura.', 'published', 5, 'Feito à mão em MDF de 18 mm. Mantenha em local seco; limpe com pano levemente úmido, sem imergir em água.'),
  ((select id from public.category where slug = 'especiais'), 'Risotinho', 'risotinho', 'Molde para prato de risoto menor: 20 cm de diâmetro e 5,4 cm de altura.', 'published', 5, 'Feito à mão em MDF de 18 mm. Mantenha em local seco; limpe com pano levemente úmido, sem imergir em água.'),
  ((select id from public.category where slug = 'especiais'), 'Manteigueira Francesa', 'manteigueira-francesa', 'Molde para manteigueira francesa, com fundo substituível e três opções de acabamento.', 'published', 5, 'Feito à mão em MDF de 18 mm. Mantenha em local seco; limpe com pano levemente úmido, sem imergir em água.'),
  ((select id from public.category where slug = 'especiais'), 'Conjunto de Bowls', 'conjunto-de-bowls', 'Conjunto de três moldes de bowl (pequeno, médio e grande) para uma coleção completa de tigelas.', 'published', 5, 'Feito à mão em MDF de 18 mm. Mantenha em local seco; limpe com pano levemente úmido, sem imergir em água.'),
  ((select id from public.category where slug = 'especiais'), 'Copo', 'copo', 'Molde para copo com fundo substituível e três opções de acabamento. Escolha o tamanho.', 'published', 5, 'Feito à mão em MDF de 18 mm. Mantenha em local seco; limpe com pano levemente úmido, sem imergir em água.'),
  ((select id from public.category where slug = 'ferramentas'), 'Disco para Torno Inteiriço', 'disco-para-torno-inteirico', 'Disco de 31 cm em MDF naval, encaixa no torno sem folga que cause vibração nem aperto que dificulte a remoção.', 'published', 5, 'MDF naval, resistente à água. Seque após o uso e guarde em local ventilado.'),
  ((select id from public.category where slug = 'ferramentas'), 'Disco com Miolo Removível para Torno', 'disco-com-miolo-removivel-para-torno', 'Disco de 32 cm para torno com miolo removível de 20 × 20 cm, em MDF naval.', 'published', 5, 'MDF naval, resistente à água. Seque após o uso e guarde em local ventilado.'),
  ((select id from public.category where slug = 'ferramentas'), 'Descanso para Secagem', 'descanso-para-secagem', 'Placa em MDF naval para secagem e organização das peças. Escolha o tamanho.', 'published', 5, 'MDF naval, resistente à água. Seque após o uso e guarde em local ventilado.'),
  ((select id from public.category where slug = 'ferramentas'), 'Gabarito para Corte Circular', 'gabarito-para-corte-circular', 'Gabarito para corte circular em MDF de 3 mm, com medidas de 10 a 30 cm.', 'published', 5, 'MDF comum. Mantenha em local seco; evite contato prolongado com água.'),
  ((select id from public.category where slug = 'ferramentas'), 'Régua Niveladora 6 mm (par)', 'regua-niveladora-6-mm-par', 'Par de réguas niveladoras de 6 mm em MDF naval, 40 cm de comprimento.', 'published', 5, 'MDF naval, resistente à água. Seque após o uso e guarde em local ventilado.'),
  ((select id from public.category where slug = 'ferramentas'), 'Régua Niveladora 9 mm (par)', 'regua-niveladora-9-mm-par', 'Par de réguas niveladoras de 9 mm em MDF comum, 35 cm de comprimento.', 'published', 5, 'MDF comum. Mantenha em local seco; evite contato prolongado com água.'),
  ((select id from public.category where slug = 'ferramentas'), 'Régua Niveladora 3 mm (par)', 'regua-niveladora-3-mm-par', 'Par de réguas niveladoras de 3 mm em MDF comum, 40 cm de comprimento.', 'published', 5, 'MDF comum. Mantenha em local seco; evite contato prolongado com água.')
on conflict (slug) do nothing;

-- ---- Variantes (tamanho / quantidade) ---------------------------------------
insert into public.product_variant
  (product_id, label, price_cents, weight_grams, length_mm, width_mm, height_mm, is_default, sort_order)
values
  ((select id from public.product where slug = 'conjunto-turmalina'), 'Conjunto', 14900, null, 280, 265, 18, true, 0),
  ((select id from public.product where slug = 'conjunto-turmalina'), 'G', 6000, null, 280, 265, 18, false, 1),
  ((select id from public.product where slug = 'conjunto-turmalina'), 'M', 5500, null, 220, 190, 18, false, 2),
  ((select id from public.product where slug = 'conjunto-turmalina'), 'P', 5000, null, 155, 145, 18, false, 3),
  ((select id from public.product where slug = 'conjunto-padre-paraiso'), 'Conjunto', 23800, null, 310, 310, 18, true, 0),
  ((select id from public.product where slug = 'conjunto-padre-paraiso'), 'GG', 6500, null, 310, 310, 18, false, 1),
  ((select id from public.product where slug = 'conjunto-padre-paraiso'), 'G', 6000, null, 255, 260, 18, false, 2),
  ((select id from public.product where slug = 'conjunto-padre-paraiso'), 'M', 5500, null, 195, 200, 18, false, 3),
  ((select id from public.product where slug = 'conjunto-padre-paraiso'), 'P', 5000, null, 155, 160, 18, false, 4),
  ((select id from public.product where slug = 'conjunto-padre-paraiso'), 'PP', 4500, null, 110, 110, 18, false, 5),
  ((select id from public.product where slug = 'conjunto-joaima'), 'Conjunto', 14900, null, 300, 200, 18, true, 0),
  ((select id from public.product where slug = 'conjunto-joaima'), 'G', 6000, null, 300, 200, 18, false, 1),
  ((select id from public.product where slug = 'conjunto-joaima'), 'M', 5500, null, 235, 160, 18, false, 2),
  ((select id from public.product where slug = 'conjunto-joaima'), 'P', 5000, null, 175, 120, 18, false, 3),
  ((select id from public.product where slug = 'conjunto-carai'), 'Conjunto', 23800, null, 275, 260, 18, true, 0),
  ((select id from public.product where slug = 'conjunto-carai'), 'GG', 6500, null, 275, 260, 18, false, 1),
  ((select id from public.product where slug = 'conjunto-carai'), 'G', 6000, null, 250, 225, 18, false, 2),
  ((select id from public.product where slug = 'conjunto-carai'), 'M', 5500, null, 210, 195, 18, false, 3),
  ((select id from public.product where slug = 'conjunto-carai'), 'P', 5000, null, 180, 165, 18, false, 4),
  ((select id from public.product where slug = 'conjunto-carai'), 'PP', 4500, null, 135, 120, 18, false, 5),
  ((select id from public.product where slug = 'conjunto-itaobim'), 'Conjunto', 14900, null, 300, 180, 18, true, 0),
  ((select id from public.product where slug = 'conjunto-itaobim'), 'G', 6000, null, 300, 180, 18, false, 1),
  ((select id from public.product where slug = 'conjunto-itaobim'), 'M', 5500, null, 265, 145, 18, false, 2),
  ((select id from public.product where slug = 'conjunto-itaobim'), 'P', 5000, null, 230, 115, 18, false, 3),
  ((select id from public.product where slug = 'conjunto-minas-novas'), 'Conjunto', 14900, null, 315, 185, 18, true, 0),
  ((select id from public.product where slug = 'conjunto-minas-novas'), 'G', 6000, null, 315, 185, 18, false, 1),
  ((select id from public.product where slug = 'conjunto-minas-novas'), 'M', 5500, null, 260, 155, 18, false, 2),
  ((select id from public.product where slug = 'conjunto-minas-novas'), 'P', 5000, null, 200, 120, 18, false, 3),
  ((select id from public.product where slug = 'conjunto-itinga'), 'Conjunto', 14900, null, 310, 270, 18, true, 0),
  ((select id from public.product where slug = 'conjunto-itinga'), 'G', 6000, null, 310, 270, 18, false, 1),
  ((select id from public.product where slug = 'conjunto-itinga'), 'M', 5500, null, 245, 200, 18, false, 2),
  ((select id from public.product where slug = 'conjunto-itinga'), 'P', 5000, null, 190, 160, 18, false, 3),
  ((select id from public.product where slug = 'conjunto-taiobeiras'), 'Conjunto', 14900, null, 300, 190, 18, true, 0),
  ((select id from public.product where slug = 'conjunto-taiobeiras'), 'G', 6000, null, 300, 190, 18, false, 1),
  ((select id from public.product where slug = 'conjunto-taiobeiras'), 'M', 5500, null, 240, 160, 18, false, 2),
  ((select id from public.product where slug = 'conjunto-taiobeiras'), 'P', 5000, null, 175, 120, 18, false, 3),
  ((select id from public.product where slug = 'conjunto-aracuai'), 'Conjunto', 14900, null, 300, 155, 18, true, 0),
  ((select id from public.product where slug = 'conjunto-aracuai'), 'G', 6000, null, 300, 155, 18, false, 1),
  ((select id from public.product where slug = 'conjunto-aracuai'), 'M', 5500, null, 250, 130, 18, false, 2),
  ((select id from public.product where slug = 'conjunto-aracuai'), 'P', 5000, null, 200, 105, 18, false, 3),
  ((select id from public.product where slug = 'conjunto-pasmado'), 'Conjunto', 23800, null, 310, 225, 18, true, 0),
  ((select id from public.product where slug = 'conjunto-pasmado'), 'GG', 6500, null, 310, 225, 18, false, 1),
  ((select id from public.product where slug = 'conjunto-pasmado'), 'G', 6000, null, 270, 170, 18, false, 2),
  ((select id from public.product where slug = 'conjunto-pasmado'), 'M', 5500, null, 220, 135, 18, false, 3),
  ((select id from public.product where slug = 'conjunto-pasmado'), 'P', 5000, null, 175, 115, 18, false, 4),
  ((select id from public.product where slug = 'conjunto-pasmado'), 'PP', 4500, null, 135, 95, 18, false, 5),
  ((select id from public.product where slug = 'circulos'), 'Conjunto', 23800, null, 380, 380, 18, true, 0),
  ((select id from public.product where slug = 'circulos'), 'GG', 6500, null, 380, 380, 18, false, 1),
  ((select id from public.product where slug = 'circulos'), 'G', 6000, null, 320, 320, 18, false, 2),
  ((select id from public.product where slug = 'circulos'), 'M', 5500, null, 260, 260, 18, false, 3),
  ((select id from public.product where slug = 'circulos'), 'P', 5000, null, 200, 200, 18, false, 4),
  ((select id from public.product where slug = 'circulos'), 'PP', 4500, null, 140, 140, 18, false, 5),
  ((select id from public.product where slug = 'quadrados'), 'Conjunto', 23800, null, 380, 380, 18, true, 0),
  ((select id from public.product where slug = 'quadrados'), 'GG', 6500, null, 380, 380, 18, false, 1),
  ((select id from public.product where slug = 'quadrados'), 'G', 6000, null, 320, 320, 18, false, 2),
  ((select id from public.product where slug = 'quadrados'), 'M', 5500, null, 260, 260, 18, false, 3),
  ((select id from public.product where slug = 'quadrados'), 'P', 5000, null, 200, 200, 18, false, 4),
  ((select id from public.product where slug = 'quadrados'), 'PP', 4500, null, 140, 140, 18, false, 5),
  ((select id from public.product where slug = 'retangulos'), 'Conjunto', 23800, null, 380, 130, 18, true, 0),
  ((select id from public.product where slug = 'retangulos'), 'GG', 6500, null, 380, 130, 18, false, 1),
  ((select id from public.product where slug = 'retangulos'), 'G', 6000, null, 320, 110, 18, false, 2),
  ((select id from public.product where slug = 'retangulos'), 'M', 5500, null, 260, 90, 18, false, 3),
  ((select id from public.product where slug = 'retangulos'), 'P', 5000, null, 200, 70, 18, false, 4),
  ((select id from public.product where slug = 'retangulos'), 'PP', 4500, null, 140, 50, 18, false, 5),
  ((select id from public.product where slug = 'elipses'), 'Conjunto', 23800, null, 325, 175, 18, true, 0),
  ((select id from public.product where slug = 'elipses'), 'GG', 6500, null, 325, 175, 18, false, 1),
  ((select id from public.product where slug = 'elipses'), 'G', 6000, null, 300, 150, 18, false, 2),
  ((select id from public.product where slug = 'elipses'), 'M', 5500, null, 275, 125, 18, false, 3),
  ((select id from public.product where slug = 'elipses'), 'P', 5000, null, 250, 100, 18, false, 4),
  ((select id from public.product where slug = 'elipses'), 'PP', 4500, null, 225, 75, 18, false, 5),
  ((select id from public.product where slug = 'paes-de-forma'), 'Conjunto', 10800, null, 230, 215, 18, true, 0),
  ((select id from public.product where slug = 'paes-de-forma'), 'G', 6000, null, 230, 215, 18, false, 1),
  ((select id from public.product where slug = 'paes-de-forma'), 'P', 5500, null, 175, 160, 18, false, 2),
  ((select id from public.product where slug = 'pizza'), 'Único', 5500, null, 230, 190, 18, true, 0),
  ((select id from public.product where slug = 'ovos'), 'Conjunto', 14900, null, 260, 190, 18, true, 0),
  ((select id from public.product where slug = 'ovos'), 'G', 6000, null, 260, 190, 18, false, 1),
  ((select id from public.product where slug = 'ovos'), 'M', 5500, null, 220, 160, 18, false, 2),
  ((select id from public.product where slug = 'ovos'), 'P', 5000, null, 180, 130, 18, false, 3),
  ((select id from public.product where slug = 'ovo-frito-com-gema'), 'Único', 6500, null, 245, 200, 18, true, 0),
  ((select id from public.product where slug = 'banana'), 'Único', 5500, null, 250, 90, 18, true, 0),
  ((select id from public.product where slug = 'limao-siciliano'), 'Único', 5500, null, 250, 195, 18, true, 0),
  ((select id from public.product where slug = 'maca'), 'Único', 5500, null, 250, 205, 18, true, 0),
  ((select id from public.product where slug = 'pera'), 'Único', 5500, null, 245, 200, 18, true, 0),
  ((select id from public.product where slug = 'melancia'), 'Único', 5500, null, 250, 115, 18, true, 0),
  ((select id from public.product where slug = 'todas-as-frutas'), 'Conjunto', 23800, null, null, null, 18, true, 0),
  ((select id from public.product where slug = 'capivaras'), 'Conjunto', 10800, null, 245, 155, 18, true, 0),
  ((select id from public.product where slug = 'capivaras'), 'G', 6000, null, 245, 155, 18, false, 1),
  ((select id from public.product where slug = 'capivaras'), 'P', 5500, null, 180, 115, 18, false, 2),
  ((select id from public.product where slug = 'gatinhos'), 'Conjunto', 10800, null, 230, 195, 18, true, 0),
  ((select id from public.product where slug = 'gatinhos'), 'G', 5500, null, 230, 195, 18, false, 1),
  ((select id from public.product where slug = 'gatinhos'), 'P', 5000, null, 180, 155, 18, false, 2),
  ((select id from public.product where slug = 'conchas'), 'Conjunto', 14900, null, 280, 255, 18, true, 0),
  ((select id from public.product where slug = 'conchas'), 'G', 6000, null, 280, 255, 18, false, 1),
  ((select id from public.product where slug = 'conchas'), 'M', 5500, null, 200, 180, 18, false, 2),
  ((select id from public.product where slug = 'conchas'), 'P', 5000, null, 120, 110, 18, false, 3),
  ((select id from public.product where slug = 'ursinhos'), 'Conjunto', 10800, null, 230, 195, 18, true, 0),
  ((select id from public.product where slug = 'ursinhos'), 'G', 6000, null, 230, 195, 18, false, 1),
  ((select id from public.product where slug = 'ursinhos'), 'P', 5500, null, 180, 155, 18, false, 2),
  ((select id from public.product where slug = 'bonecos-de-biscoito'), 'Conjunto', 14900, null, 270, 210, 18, true, 0),
  ((select id from public.product where slug = 'bonecos-de-biscoito'), 'G', 6000, null, 270, 210, 18, false, 1),
  ((select id from public.product where slug = 'bonecos-de-biscoito'), 'M', 5500, null, 230, 180, 18, false, 2),
  ((select id from public.product where slug = 'bonecos-de-biscoito'), 'P', 5000, null, 190, 150, 18, false, 3),
  ((select id from public.product where slug = 'estrelas'), 'Conjunto', 14900, null, 310, 300, 18, true, 0),
  ((select id from public.product where slug = 'estrelas'), 'G', 6000, null, 310, 300, 18, false, 1),
  ((select id from public.product where slug = 'estrelas'), 'M', 5500, null, 255, 245, 18, false, 2),
  ((select id from public.product where slug = 'estrelas'), 'P', 5000, null, 205, 200, 18, false, 3),
  ((select id from public.product where slug = 'arvore-de-natal'), 'Único', 5500, null, null, null, 18, true, 0),
  ((select id from public.product where slug = 'coracoes'), 'Conjunto', 10800, null, 260, 220, 18, true, 0),
  ((select id from public.product where slug = 'coracoes'), 'G', 6000, null, 260, 220, 18, false, 1),
  ((select id from public.product where slug = 'coracoes'), 'P', 5500, null, 200, 170, 18, false, 2),
  ((select id from public.product where slug = 'luas'), 'Conjunto', 10800, null, 250, 125, 18, true, 0),
  ((select id from public.product where slug = 'luas'), 'G', 6000, null, 250, 125, 18, false, 1),
  ((select id from public.product where slug = 'luas'), 'P', 5500, null, 250, 90, 18, false, 2),
  ((select id from public.product where slug = 'nuvens'), 'Conjunto', 10800, null, 225, 160, 18, true, 0),
  ((select id from public.product where slug = 'nuvens'), 'Nuvem A', 5500, null, 225, 160, 18, false, 1),
  ((select id from public.product where slug = 'nuvens'), 'Nuvem B', 5500, null, 260, 145, 18, false, 2),
  ((select id from public.product where slug = 'barcos'), 'Conjunto', 10800, null, 420, 220, 18, true, 0),
  ((select id from public.product where slug = 'barcos'), 'G', 6000, null, 420, 220, 18, false, 1),
  ((select id from public.product where slug = 'barcos'), 'P', 5500, null, 275, 155, 18, false, 2),
  ((select id from public.product where slug = 'canoa'), 'Único', 5500, null, 385, 90, 18, true, 0),
  ((select id from public.product where slug = 'conjunto-sushi-arredondado'), 'Conjunto', 14900, null, 330, 130, 18, true, 0),
  ((select id from public.product where slug = 'conjunto-sushi-arredondado'), 'G', 6000, null, 330, 130, 18, false, 1),
  ((select id from public.product where slug = 'conjunto-sushi-arredondado'), 'M', 5500, null, 200, 200, 18, false, 2),
  ((select id from public.product where slug = 'conjunto-sushi-arredondado'), 'P', 5000, null, 80, 80, 18, false, 3),
  ((select id from public.product where slug = 'conjunto-sushi-reto'), 'Conjunto', 14900, null, 330, 130, 18, true, 0),
  ((select id from public.product where slug = 'conjunto-sushi-reto'), 'G', 6000, null, 330, 130, 18, false, 1),
  ((select id from public.product where slug = 'conjunto-sushi-reto'), 'M', 5500, null, 200, 200, 18, false, 2),
  ((select id from public.product where slug = 'conjunto-sushi-reto'), 'P', 5000, null, 80, 80, 18, false, 3),
  ((select id from public.product where slug = 'prato-de-risoto'), 'Único', 15000, null, 310, 310, 72, true, 0),
  ((select id from public.product where slug = 'risotinho'), 'Único', 12000, null, 200, 200, 54, true, 0),
  ((select id from public.product where slug = 'manteigueira-francesa'), 'Único', 13000, null, 75, 75, 90, true, 0),
  ((select id from public.product where slug = 'conjunto-de-bowls'), 'Conjunto', 40000, null, 250, 250, 90, true, 0),
  ((select id from public.product where slug = 'copo'), 'Pequeno', 11000, null, 60, 60, 90, false, 0),
  ((select id from public.product where slug = 'copo'), 'Médio', 13000, null, 75, 75, 90, true, 1),
  ((select id from public.product where slug = 'copo'), 'Grande', 15000, null, 90, 90, 90, false, 2),
  ((select id from public.product where slug = 'disco-para-torno-inteirico'), '1 unidade', 3500, null, 310, 310, 6, true, 0),
  ((select id from public.product where slug = 'disco-para-torno-inteirico'), '3 unidades', 10000, null, 310, 310, 6, false, 1),
  ((select id from public.product where slug = 'disco-para-torno-inteirico'), '5 unidades', 16000, null, 310, 310, 6, false, 2),
  ((select id from public.product where slug = 'disco-para-torno-inteirico'), '10 unidades', 31000, null, 310, 310, 6, false, 3),
  ((select id from public.product where slug = 'disco-com-miolo-removivel-para-torno'), '1 disco + 1 miolo', 5500, null, 320, 320, 6, true, 0),
  ((select id from public.product where slug = 'disco-com-miolo-removivel-para-torno'), '1 disco + 5 miolos', 14000, null, 320, 320, 6, false, 1),
  ((select id from public.product where slug = 'disco-com-miolo-removivel-para-torno'), '1 disco + 10 miolos', 25000, null, 320, 320, 6, false, 2),
  ((select id from public.product where slug = 'disco-com-miolo-removivel-para-torno'), '1 disco + 15 miolos', 34000, null, 320, 320, 6, false, 3),
  ((select id from public.product where slug = 'descanso-para-secagem'), '10 × 10 cm', 500, null, 100, 100, 6, true, 0),
  ((select id from public.product where slug = 'descanso-para-secagem'), '15 × 15 cm', 700, null, 150, 150, 6, false, 1),
  ((select id from public.product where slug = 'descanso-para-secagem'), '20 × 20 cm', 1100, null, 200, 200, 6, false, 2),
  ((select id from public.product where slug = 'descanso-para-secagem'), '25 × 25 cm', 1700, null, 250, 250, 6, false, 3),
  ((select id from public.product where slug = 'descanso-para-secagem'), '30 × 30 cm', 2400, null, 300, 300, 6, false, 4),
  ((select id from public.product where slug = 'descanso-para-secagem'), '35 × 35 cm', 3200, null, 350, 350, 6, false, 5),
  ((select id from public.product where slug = 'descanso-para-secagem'), '40 × 40 cm', 4000, null, 400, 400, 6, false, 6),
  ((select id from public.product where slug = 'descanso-para-secagem'), '20 × 10 cm', 600, null, 200, 100, 6, false, 7),
  ((select id from public.product where slug = 'descanso-para-secagem'), '30 × 15 cm', 1300, null, 300, 150, 6, false, 8),
  ((select id from public.product where slug = 'descanso-para-secagem'), '40 × 20 cm', 2200, null, 400, 200, 6, false, 9),
  ((select id from public.product where slug = 'gabarito-para-corte-circular'), 'Único', 7000, null, 300, 300, 3, true, 0),
  ((select id from public.product where slug = 'regua-niveladora-6-mm-par'), 'Único', 2500, null, 400, 40, 6, true, 0),
  ((select id from public.product where slug = 'regua-niveladora-9-mm-par'), 'Único', 2500, null, 350, 40, 9, true, 0),
  ((select id from public.product where slug = 'regua-niveladora-3-mm-par'), 'Único', 2500, null, 400, 40, 3, true, 0)
on conflict do nothing;

